### ISSUE TITLE
Sync or backup

### ISSUE THREAD

**Issue by jcrabapple** [DarkMooNight/ToDark#7]
This app is amazing! The only thing missing is the ability to sync tasks with a calendar and create backups.

**Comment by Leonavichus** [comment]
Hi, thanks for the feedback, I will try to make a backup of the database. Do you mean sync with google calendar?

**Comment by jcrabapple** [comment]
Preferably CalDAV since I use Fastmail for calendar. Thank you.

**Comment by danielyrovas** [comment]
CalDAV would certainly be an interesting method of syncing a todo application.

I currently use `todo.txt` from [todotxt.org](http://todotxt.org) to save my todos as a file and sync with syncthing. Would it be possible to sync the todos to and from a text file so that it can be synced to laptop/pc with syncthing?

**Comment by Leonavichus** [comment]
I don't know yet, I'll have to check and see.

**Comment by Leonavichus** [comment]
I have published a release with backup and data recovery, the database I use does not support the export of links, but they seem to be working on it. So for now I keep all the tasks in a separate category.

**Comment by mrexojo** [comment]
Sorry, new functionality backup doesn't work on sd-card. It aske to allow like other apps, but it crash when I set the sd-card folder. Ssme for Internal storage: "something went wrong "

**Comment by Leonavichus** [comment]
I'll see what I can do.
